In [5]:
import numpy as np
import pandas as pd

### 1. Consider the following Python dictionary data and Python list labels:

In [6]:
data = {'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills', 'Cranes'], 
        'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4, 3.5], 'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2, 2], 
        'priority': ['yes', 'yes', 'no', np.nan, 'no', 'no', 'no', 'yes', 'no', 'no','yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']

#### *i) Create a DataFrame birds from the above dictionary data which has the index labels.*

In [17]:
birds = pd.DataFrame(data, index=labels)
birds

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      NaN
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no
k      Cranes  3.5       2      yes

#### *ii) Display basic information about the dataFrame.*

In [18]:
birds.info()
birds.describe(include='all')

<class 'pandas.DataFrame'>
Index: 11 entries, a to k
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   birds     11 non-null     str
 1   age       9 non-null      float64
 2   visits    11 non-null     int64
 3   priority  10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 440.0+ bytes

         birds       age     visits priority
count       11  9.000000  11.000000       10
unique       3       NaN        NaN        2
top     Cranes       NaN        NaN       no
freq         5       NaN        NaN        6
mean       NaN  4.333333   2.818182      NaN
std        NaN  1.903943   0.873863      NaN
min        NaN  1.500000   2.000000      NaN
25%        NaN  3.500000   2.000000      NaN
50%        NaN  4.000000   3.000000      NaN
75%        NaN  5.500000   3.500000      NaN
max        NaN  8.000000   4.000000      NaN

#### *iii) Show Alternate rows of the dataframe.*

In [19]:
birds.iloc[::2]

        birds  age  visits priority
a      Cranes  3.5       2      yes
c     plovers  1.5       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
i  spoonbills  8.0       3       no
k      Cranes  3.5       2      yes

#### *iv) Show only rows [1st, 3rd, 7th] from columns ['bird', 'age']*

In [20]:
birds.iloc[[0, 2, 6]][['birds', 'age']]

     birds  age
a   Cranes  3.5
c  plovers  1.5
g  plovers  5.5

#### *v) Select rows where the number of visits is less than 4.*

In [21]:
birds[birds['visits'] < 4]

        birds  age  visits priority
a      Cranes  3.5       2      yes
c     plovers  1.5       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no
k      Cranes  3.5       2      yes

#### *vi) Select all rows with nan values in age and priority column.*

In [22]:
birds[birds['age'].isna() & birds['priority'].isna()]

        birds  age  visits priority
d  spoonbills  NaN       4      NaN

#### *vii) Fill nan with respective series mode value.*

In [23]:
for col in ['age', 'priority']:
    birds[col] = birds[col].fillna(birds[col].mode()[0])

birds

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  3.5       4       no
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  3.5       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no
k      Cranes  3.5       2      yes

#### *viii) Find the total number of visits of the bird Cranes.*

In [24]:
birds.loc[birds['birds'] == 'Cranes', 'visits'].sum()

np.int64(14)

#### *ix) Find the number of each type of birds in dataframe.*

In [25]:
birds['birds'].value_counts()

birds
Cranes        5
spoonbills    4
plovers       2
Name: count, dtype: int64

#### *x) Print no of duplicate rows.*

In [26]:
birds.duplicated().sum()

np.int64(2)

#### *xi) Drop Duplicates rows and make this changes permanent. Show dataframe after changes.*

In [27]:
birds.drop_duplicates(inplace=True)
birds

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  3.5       4       no
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no

### 2.  Download this dataset: `IPL dataset from 2008 to 2022.`
https://drive.google.com/file/d/10_eb5Dy81iXO-aTd4LDRUk85jHVLsqGb/view?usp=drive_link

`After downloading, kindly upload the dataset to the same folder that contains this file.`

In [28]:
# Read dataset and display top 5 rows
ipl = pd.read_csv('Dataset/IPL_Matches_2008_2022.csv')
ipl.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

##### *In IPL matches dataset some teams name has changed. We will have to consider them as same.*

Change `Delhi Daredevils` -> `Delhi Capitals` <br>
Change `Kings XI Punjab` -> `Punjab Kings` <br>
Change `Rising Pune Supergiants` -> `Rising Pune Supergiant` <br>
*We need to make changes accordingly. Consider current name for each teams.*

Be careful `Gujrat Titans` and `Gujrat Lions` are different teams.

In [29]:
team_name_map = {
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Rising Pune Supergiants': 'Rising Pune Supergiant'
}

team_cols = ['Team1', 'Team2', 'TossWinner', 'WinningTeam']
ipl[team_cols] = ipl[team_cols].replace(team_name_map)
ipl[['Team1', 'Team2', 'WinningTeam']].head()

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings

#### *i) Display the bar chart of top 5 teams who have played maximum number of matches in the IPL.*
`Hint:` Be careful the data is divided in 2 different cols(Team 1 and Team 2)

In [30]:
top_teams = pd.concat([ipl['Team1'], ipl['Team2']]).value_counts().head(5)
top_teams_df = top_teams.rename('Matches_Played').to_frame()
scale = 40 / top_teams_df['Matches_Played'].max()
top_teams_df['Bar'] = top_teams_df['Matches_Played'].apply(lambda x: '#' * int(np.ceil(x * scale)))
top_teams_df

,Matches_Played,Bar
Mumbai Indians,231,########################################
Royal Challengers Bangalore,226,########################################
Delhi Capitals,224,#######################################
Kolkata Knight Riders,223,#######################################
Punjab Kings,218,######################################

#### *ii) Player who got Most no. of player of the match award playing against Mumbai Indians.*

In [10]:
vs_mi = ipl[(ipl['Team1'] == 'Mumbai Indians') | (ipl['Team2'] == 'Mumbai Indians')]
vs_mi['Player_of_Match'].value_counts().head(1)

Player_of_Match
RG Sharma    16
Name: count, dtype: int64

#### *iii) Find out the top 7 cities where the matches of Kolkata Knight Riders are played frequently <br> and plot the result as bar chart.*

In [13]:
kkr_matches = ipl[(ipl['Team1'] == 'Kolkata Knight Riders') | (ipl['Team2'] == 'Kolkata Knight Riders')]
top_cities = kkr_matches['City'].value_counts().head(7)
top_cities_df = top_cities.rename('Match_Count').to_frame()
scale = 40 / top_cities_df['Match_Count'].max()
top_cities_df['Bar'] = top_cities_df['Match_Count'].apply(lambda x: '#' * int(np.ceil(x * scale)))
top_cities_df

           Match_Count                                       Bar
City
Kolkata             74  ########################################
Mumbai              23                             #############
Abu Dhabi           14                                  ########
Chennai             12                                   #######
Bangalore           11                                    ######
Delhi               10                                    ######
Pune                 9                                     #####

#### *iv) Find out the average margin for the team Mumbai Indians for only the session 2011.*

In [33]:
mi_2011 = ipl[
    ((ipl['Team1'] == 'Mumbai Indians') | (ipl['Team2'] == 'Mumbai Indians'))
    & (ipl['Season'].astype(str) == '2011')
]

mi_2011['Margin'] = pd.to_numeric(mi_2011['Margin'], errors='coerce')
mi_2011['Margin'].mean()

np.float64(19.25)

#### *v) Team1 vs Team2 Dashbord*

*Create a function which will take two string(name of two teams) as input. Show win Loss record between them <br>
and player getting most player of the match award in matches between these two teams.* <br>
`team1_vs_team2('Kolkata Knight Riders','Chennai Super Kings')`

In [32]:
def team1_vs_team2(team1, team2):
    matches = ipl[
        ((ipl['Team1'] == team1) & (ipl['Team2'] == team2))
        | ((ipl['Team1'] == team2) & (ipl['Team2'] == team1))
    ]

    if matches.empty:
        print(f'No matches found between {team1} and {team2}.')
        return

    print(f'Total matches between {team1} and {team2}: {len(matches)}')
    print('\nWin/Loss record:')
    print(matches['WinningTeam'].value_counts(dropna=False))

    print('\nTop Player of the Match:')
    print(matches['Player_of_Match'].value_counts().head(1))

In [31]:
team1_vs_team2('Kolkata Knight Riders', 'Chennai Super Kings')

Total matches between Kolkata Knight Riders and Chennai Super Kings: 26

Win/Loss record:
WinningTeam
Chennai Super Kings      17
Kolkata Knight Riders     9
Name: count, dtype: int64

Top Player of the Match:
Player_of_Match
RA Jadeja    3
Name: count, dtype: int64